### ISSUE TITLE
디바이스 추가

### ISSUE THREAD

**Issue by lunDreame** [zmtq05/kocom_wallpad#18]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/zmtq05/kocom_wallpad/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

X

### Describe the solution you'd like

X

### Describe alternatives you've considered

코콤 장치 추가패킷 래퍼런스

### Additional context

X

**Comment by zmtq05** [comment]
제게 기기가 없어서 테스트가 불가능합니다.

그 기기가 rs485 통신을 하나요?

**Comment by lunDreame** [comment]
모두 월패드 통신내에 포함되어 있어요. 집가서 코드보고 pr이나 패킷 데이터 올려드릴게요

**Comment by zmtq05** [comment]
알겠습니다

**Comment by lunDreame** [comment]
# Device Mapping and Value Parsing Guide

## Device List
- **0x98**: Indoor Air Quality Information
- **0x39**: Air Conditioner
- **0x3B**: Outlet (same parsing method as lighting)
- **0x33**: Kitchen Phone
- **0x36**: Thermostat
---

## Indoor Air Quality Information (Device: 0x98)

**Value Mapping (8 bytes):**
| Index | Parameter       | Description                     | Conversion          |
|-------|-----------------|---------------------------------|---------------------|
| 0     | `pm10`          | Particulate Matter (10µm)       | Decimal             |
| 1     | `pm25`          | Particulate Matter (2.5µm)      | Decimal             |
| 2-3   | `co2`           | Carbon Dioxide                 | Decimal (2 bytes)   |
| 4-5   | `voc`           | Volatile Organic Compounds      | Decimal (2 bytes)   |
| 6     | `temperature`   | Temperature (°C)               | Decimal             |
| 7     | `humidity`      | Humidity (%)                   | Decimal             |

---

## Air Conditioner (Device: 0x39)

**Value Mapping:**
| Index | Parameter          | Description                | Value                      |
|-------|--------------------|----------------------------|----------------------------|
| 0     | Power Status       | Power On/Off              | `0x10`: On / Off           |
| 1     | Operation Mode     | Cooling, Fan, Dry, Auto   | `0x00`: Cooling, `0x01`: Fan Only, `0x02`: Dry, `0x03`: Auto |
| 2     | Fan Speed          | Fan speed levels          | `0x01`: Low, `0x02`: Medium, `0x03`: High |
| 4     | Current Temperature| Current room temperature  | Decimal                    |
| 5     | Target Temperature | Set temperature           | Decimal                    |

---

## Outlet (Device: 0x3B)

Parsing method is identical to that used for lighting.

---

## Kitchen Phone (Device: 0x33)

-

---

## Thermostat (Device: 0x36)

**Value Mapping (8 bytes):**
| Index | Parameter         | Description                 | Conversion |
|-------|-------------------|-----------------------------|------------|
| 3     | `hot_water`       | Hot water (or heating water if absent) | Decimal    |
| 5     | `heating_water`   | Heating water temperature   | Decimal    |

---

### Notes
- Ensure all values are converted to decimal format where applicable.
- For multi-byte values (e.g., `co2`, `voc`), combine bytes before conversion.

**Comment by lunDreame** [comment]
바빠서 못 올렸었네요ㅜ 기억이 가물가물해서 틀릴 수도 있어요. 참고해서 봐주세요

**Comment by zmtq05** [comment]
각 장치마다 예시가 필요합니다.
장치가 여러개 있는지의 여부도 필요합니다.
thermostat의 각 parameter 는 무슨 뜻인가요?

**Comment by lunDreame** [comment]
공기질의 경우 하나만 있으며, 나머지의 경우 n개 입니다. 코콤 난방 패킷에 온수, 난방수 온도가 올라오는거 같습니다. 검증은 못해봤어요. 해당 위치의 값이 0이상이라면 지원하는듯 합니다.

**Comment by lunDreame** [comment]
넵

**Comment by lunDreame** [comment]
저도 임시로 만들면서 확인중인데 온수/난방수 조절도 가능한듯해요. 온수/난방수가 올라오면 제어 가능하고요. 저희집은 안올라 오네요. 

확인 한번 해보시면 될듯합니다.

**Comment by zmtq05** [comment]
정보가 부족한 `kitchen phone`, `thermostat`을 제외한 엔티티를 해당 [브랜치](https://github.com/zmtq05/kocom_wallpad/tree/feat-additional-devices)에 업데이트 했습니다.

**Comment by lunDreame** [comment]
잘 되는거 같습니다. 일단 이슈는 닫도록 하겠습니다.
